add a type variable, and remove mypy ignore
opendp/opendp pull request #1424
Opened 2024-03-21 19:28 UTC by mccalluc

- Fix #1411

FYI: The rendered docs do not show the type variable:

> Return type:
> 
>     Tuple[Measure, float | Tuple[float, float]]

2024-03-21 19:36 UTC, Shoeboxam requested changes

2024-03-21 19:36 UTC, Shoeboxam commented on python/src/opendp/context.py
> +LossParameter = float | Tuple[float, float]
I dont think this will work before 3.10 without `from __future__ import annotations`?

2024-04-10 18:03 UTC, mccalluc commented
Lots of failures: All look like:
```
ValueError: predicate always fails. An example traceback is shown above at 0.0.
```

This PR has drifted: Maybe refocus on just getting the type annotation right, before trying to make it elegant.

2024-04-23 18:37 UTC, mccalluc commented
- Close in favor of #1524

2024-04-23 18:37 UTC, closed without merging