don't cargo test in rust-build smoke-test
opendp/opendp pull request #1579
Opened 2024-05-02 19:58 UTC by Shoeboxam

2024-05-02 19:59 UTC, Shoeboxam commented
* **#1579** <a href="https://app.graphite.dev/github/pr/opendp/opendp/1579?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Shoeboxam and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-05-02 23:57 UTC, mccalluc requested changes
Really uncomfortable dropping the tests... Maybe something else covers this logic, but I don't think we know.

(But overall, thanks for looking into this!)

2024-05-02 23:57 UTC, mccalluc commented on .github/workflows/smoke-test.yml
> +      # - name: Free disk space
```suggestion
      # We're no longer running out of space, but freeing disk space uses time, so disable. Re-enable if needed.
      # - name: Free disk space
```

2024-05-02 23:57 UTC, mccalluc commented on .github/workflows/smoke-test.yml
> +      # - name: Free disk space
```suggestion
      # We're no longer running out of space, but freeing disk space uses time, so disable. Re-enable if needed.
      # - name: Free disk space
```

2024-05-02 23:57 UTC, mccalluc commented on .github/workflows/smoke-test.yml
> +        run: cargo test --verbose --all-features --lib
```suggestion
        run: cargo test --verbose --all-features
```
I'm uncomfortable disabling doctests entirely right now. Maybe hold off on this part?
- Are there particular doctests that are using a lot of time, or is it simply that doctests in general are slow to run? Sometimes just a couple tests dominate.
- If they are dropped from smoke test, could we make sure they are run nightly? Might already be the case.
- Do we want to discourage doctests going forward? Or only use them on high visibility functions? Or make sure that single doctests cover a lot of ground, to make up for the compilation cost?

2024-05-03 13:27 UTC, Shoeboxam commented
Maybe things will speed up in the future with https://github.com/rust-lang/rust/issues/75341.

In the meantime I might open a PR that moves some doctests to unit tests.

2024-05-03 14:10 UTC, mccalluc approved these changes
Thanks!

2024-05-03 14:26 UTC, merged