Require honest-but-curious note
opendp/opendp pull request #1664
Opened 2024-06-06 14:29 UTC by mccalluc

- Eventually, fix #1662
- For now, draft: Just want to get feedback on this approach.
- If good, next step is to actually fill in short explanations for each method.

2024-07-16 20:04 UTC, Shoeboxam requested changes
This looks great, I left a few comments, and filled some TODOs.

2024-07-16 20:04 UTC, Shoeboxam commented on rust/src/transformations/make_user_transformation/mod.rs
> +/// Requires `honest-but-curious`: TODO
```suggestion
/// Requires `honest-but-curious`: The OpenDP Library cannot verify that the stability of the resulting transformation is governed by the provided stability map.
```

2024-07-16 20:04 UTC, Shoeboxam commented on rust/src/transformations/make_user_transformation/mod.rs
> +/// Requires `honest-but-curious`: TODO
For measurements:

```suggestion
/// Requires `honest-but-curious`: The OpenDP Library cannot verify that the privacy of the resulting measurement is governed by the provided privacy map.
```

2024-07-16 20:04 UTC, Shoeboxam commented on rust/src/transformations/manipulation/mod.rs
> +/// Requires `honest-but-curious`: TODO
```suggestion
/// Requires `honest-but-curious`: The resulting transformation is only valid if the input domain and input metric form a metric space.
```

2024-07-16 20:48 UTC, Shoeboxam requested changes
From Salil, would you also mind updating the text for honest-but-curious? 

> Enable to include constructors whose differential privacy (or stability) properties rely on the constructor arguments being correct.  That is, if a user/adversary is 'honest' in specifying the constructor arguments, then even if they later become 'curious' and try to learn something from the measurement outputs, they will not be able to violate the differential privacy promises of the measurement.

2024-07-17 20:34 UTC, mccalluc commented
Salil's revised text made it in #1810. I'll try to address the other points here.

2024-07-17 20:45 UTC, mccalluc commented on rust/opendp_tooling/src/bootstrap/docstring.rs
> +        panic!("In {name} doc comment, add '{requires} because ...'")
Will do. Is the idea that even if I think an error is unrecoverable, we don't want to make it impossible for it to be handled by the caller?

2024-07-17 21:09 UTC, mccalluc commented
Having a build error, but feel out of my depth:
```
error: unexpected end of macro invocation
  --> opendp_derive/src/full.rs:62:85
   |
15 | macro_rules! try_ {
   | ----------------- when calling this macro
...
62 |         try_!(confirm_note_for_honest_but_curious(function.name, &mut item_fn.attrs));
   |                                                                                     ^ missing tokens in macro arguments
   |
note: while trying to match `,`
  --> opendp_derive/src/full.rs:16:16
   |
16 |     ($expr:expr, $original:expr) => {
   |                ^
```

2024-09-06 13:33 UTC, mccalluc commented
Closing this PR.
- #2014 

seems sufficient to me, and it is less of a maintenance burden. If anyone strongly believes that we should also require an explanation of why a particular feature is required for a particular function, file a new issue.

2024-09-06 13:33 UTC, closed without merging