Add a little more explanation for honest-but-curious
opendp/opendp pull request #1730
Opened 2024-06-25 13:27 UTC by mccalluc

- Fix #1227

2024-06-25 16:53 UTC, Shoeboxam requested changes
I moved pop amplification first, as plugins are not quite as user-facing. Nitted wording of amplification because it mainly depends on the sample being a simple sample.

Thanks!

2024-06-25 16:53 UTC, Shoeboxam commented on docs/source/contributing/development-environment.rst
> +            Similarly, population amplification relies on an honest population size.
```suggestion
            For example, population amplification must assume the user is honest and correct in their assertion that the dataset under observation is a simple sample.
            Similarly, library plugins must assume that the privacy or stability of a given function is governed by the given map.
```

2024-06-26 00:35 UTC, mccalluc commented on docs/source/contributing/development-environment.rst
> +            Similarly, population amplification relies on an honest population size.
Sounds good. Thanks!

2024-07-16 19:38 UTC, Shoeboxam approved these changes
Great!

2024-07-16 19:38 UTC, merged