remove generics from measures
opendp/opendp pull request #1768
Opened 2024-07-08 23:29 UTC by Shoeboxam

Closes #1737

2024-07-08 23:29 UTC, Shoeboxam commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/opendp/opendp/1768?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1768** <a href="https://app.graphite.dev/github/pr/opendp/opendp/1768?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#1716** <a href="https://app.graphite.dev/github/pr/opendp/opendp/1716?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 1 other dependent PR ([#1767](https://github.com/opendp/opendp/pull/1767) <a href="https://app.graphite.dev/github/pr/opendp/opendp/1767?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* **#1760** <a href="https://app.graphite.dev/github/pr/opendp/opendp/1760?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1703** <a href="https://app.graphite.dev/github/pr/opendp/opendp/1703?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>: 2 other dependent PRs ([#1715](https://github.com/opendp/opendp/pull/1715) <a href="https://app.graphite.dev/github/pr/opendp/opendp/1715?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>, [#1732](https://github.com/opendp/opendp/pull/1732) <a href="https://app.graphite.dev/github/pr/opendp/opendp/1732?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>)
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Shoeboxam and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-05 20:32 UTC, mccalluc requested changes
I'll give this a closer look, but one immediate problem with the docs build.

2024-09-05 20:32 UTC, mccalluc commented on rust/src/measures/ffi.rs
> +/// ```
This is probably causing the CI failure:
```
/home/runner/work/opendp/opendp/python/src/opendp/measures.py:
docstring of opendp.measures.approximate:21:
WARNING: Pygments lexer name 'math' is not known
```

2024-09-05 20:42 UTC, mccalluc reviewed
Otherwise, looks ok. Let me know if there's anything to look at closely.

2024-09-06 19:06 UTC, mccalluc approved these changes
Looks good.

2024-09-09 22:41 UTC, Shoeboxam commented on R/opendp/vignettes_old/comb.Rmd
>  #    print(meas.map(1.))
Yep. Might as well update it if relevant. Best to just remove though.

2024-09-11 03:46 UTC, merged