Make getting-started/stats
opendp/opendp pull request #1799
Opened 2024-07-16 17:33 UTC by mccalluc

- Fix #1773
- Surprised PCA is missing in reference: Just filed #1798 
- #1770 might be referenced here

2024-07-16 21:20 UTC, Shoeboxam requested changes
Minor comments.

2024-07-16 21:20 UTC, Shoeboxam commented on docs/source/getting-started/stats/index.rst
> +Statistical Modelling
Can we use US English (one "l")? Sorry UK folks!

2024-07-16 21:20 UTC, Shoeboxam commented on docs/source/getting-started/stats/index.rst
> +Others, like PCA, are supported under the ``opendp.sklearn`` namespace.
I would say that we intend to provide more functionality in this space in the future and are accepting contributions. For the time being, we have PCA and consider it a model for future functionality.

2024-07-16 21:20 UTC, Shoeboxam commented on docs/source/getting-started/stats/pca.ipynb
Did this get converted? Might need to be rebased.

2024-07-17 19:42 UTC, mccalluc reviewed
updated text

2024-07-17 19:42 UTC, mccalluc commented on docs/source/getting-started/stats/index.rst
> +Statistical Modelling
```suggestion
Statistical Modeling
```

2024-07-17 19:42 UTC, mccalluc commented on docs/source/getting-started/stats/index.rst
> +Others, like PCA, are supported under the ``opendp.sklearn`` namespace.
```suggestion
We intend to provide more functionality in this space in the future and are accepting contributions.
For the time being, OpenDP has PCA and we consider it a model for future functionality.
```

2024-07-18 02:29 UTC, Shoeboxam approved these changes
Thanks!

2024-07-18 02:29 UTC, merged