Refactor extras.sklearn for consistency
opendp/opendp pull request #1866
Opened 2024-07-31 20:50 UTC by mccalluc

Follow-up to:
- #1452

Introduces `sklearn.pca` and puts everything PCA-related under it. The idea is that other sklearn topics might get their own submodules. This structure is really driven by the documentation: I've moved the private methods along with the public, but they could live in a separate file/directory.

2024-07-31 21:34 UTC, Shoeboxam requested changes

2024-07-31 21:34 UTC, Shoeboxam commented on python/src/opendp/extras/sklearn/pca/__init__.py
Technically make_private_pca (and all other make_ functions in this module) don't need sklearn. Although I guess the organizational convenience is better than being technically tighter.

2024-07-31 21:34 UTC, Shoeboxam commented on python/src/opendp/extras/sklearn/pca/__init__.py
I think it would be better to leave `make_pca` in its current location, and add a `decomposition` module for the PCA class, to more closely match the SciKit-Learn API.

2024-07-31 21:37 UTC, Shoeboxam commented on python/src/opendp/extras/sklearn/pca/__init__.py
I feel less strongly about the location of `make_` APIs, but we might as well organize SciKit-Learn mimicry in the same way SciKit-Learn does.

2024-08-01 15:15 UTC, Shoeboxam commented on python/src/opendp/extras/sklearn/pca/__init__.py
https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html

2024-08-01 21:54 UTC, mccalluc commented on python/src/opendp/extras/sklearn/pca/__init__.py
> I think it would be better to leave `make_pca` in its current location

Not sure if you mean the state on main, or the state in this branch? PCA should now be in the right place, though.

2024-08-02 02:15 UTC, Shoeboxam approved these changes
Thanks for the iterations. Locations of public code seems good to me at this point. 
Conflict should resolve once GitHub rebases this PR in merge.

2024-08-02 13:23 UTC, merged