Fix links for Title IX and Maintainer Notes
opendp/opendp pull request #2013
Opened 2024-09-03 13:34 UTC by mccalluc

- Fix #2012

I'll DM Sharon on Slack about the best replacement for the Title IX link, and would like a thumbs up from her before merging.

2024-09-03 15:13 UTC, Shoeboxam requested changes
From Chuck, Sharon gave thumbs up on pointing to SEAS.

2024-09-03 15:13 UTC, Shoeboxam commented on .github/workflows/README.md
> +provides a broader view of the the develpment and release process.
I think I'd just drop this, since we dropped those docs.

2024-09-03 15:13 UTC, Shoeboxam commented on .github/workflows/README.md
>  OpenDP uses a number of Github workflows: Some are started automaticly
```suggestion
OpenDP uses a number of Github workflows: Some are started automatically
```

2024-09-03 18:33 UTC, mccalluc commented on .github/workflows/README.md
> +provides a broader view of the the develpment and release process.
```suggestion
```

2024-09-04 15:25 UTC, Shoeboxam approved these changes
Thanks for the edits!

2024-09-04 16:41 UTC, merged