review: sample_geometric_exp_fast
opendp/opendp pull request #2117
Opened 2024-10-22 01:48 UTC by Shoeboxam

Towards #2069

2024-10-22 01:48 UTC, Shoeboxam commented
* **#2117** <a href="https://app.graphite.dev/github/pr/opendp/opendp/2117?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @Shoeboxam and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-12-21 17:25 UTC, michaelghay commented
[sample_geometric_exp_fast.pdf](https://github.com/user-attachments/files/18219405/sample_geometric_exp_fast.pdf)

2025-10-02 12:53 UTC, mccalluc commented
@Shoeboxam , can you respond to the suggested changes in the attached PDF? Thanks!

2025-12-22 21:17 UTC, tholop requested changes
The final proof still needs some changes as noted by Michael. I made some suggestions to help for that, and also suggested minor fixes.

2025-12-22 21:17 UTC, tholop commented on rust/src/traits/samplers/cks20/sample_geometric_exp_fast.tex
> +    \texttt{x} is of type \docsrs{rug}{struct}{Rational}, there exists some non-negative integer $s$ and positive integer $t$ such that $x = s/t$.
```suggestion
    $\texttt{x} \geq 0$ and \texttt{x} is of type \docsrs{dashu}{rational/struct}{Rbig}, so there exists some non-negative integer $s$ and positive integer $t$ such that $x = s/t$. 
```

2025-12-22 21:17 UTC, tholop commented on rust/src/traits/samplers/cks20/sample_geometric_exp_fast.tex
> +    Since $t$ is a positive integer, the preconditions on \rustdoc{traits/samplers/uniform/trait}{SampleUniformIntBelow} are met,
```suggestion
    Since $t$ is a positive integer, the preconditions on \rustdoc{traits/samplers/uniform/fn}{sample_uniform_ubig_below} are met,  
```

2025-12-22 21:17 UTC, tholop commented on rust/src/traits/samplers/cks20/sample_geometric_exp_fast.tex
> +        &= P[U = u_z | D = \top] P[V = v_z] && \text{as $U$ and $V$ are independent}\\
```suggestion
        &= P[U = u_z | D = \top] P[V = v_z] && \text{as $U$ and $V$ are independent, and $V$ and $D$ are independent}\\ 
```

2025-12-22 21:17 UTC, tholop commented on rust/src/traits/samplers/cks20/sample_geometric_exp_fast.tex
> +        &= \frac{(1 - e^{-1})}{\sum_{k=0}^{t-1}e^{-k/t}}  e^{-(u_z/t + v_z)} \\
```suggestion
        &= \frac{(1 - e^{-1})}{\sum_{k=0}^{t-1}e^{-k/t}}  e^{-(u_z/t + v_z)} \\ 
        &= \frac{(1 - e^{-1})}{(1 - (e^{-1/t})^t)/(1 - e^{-1/t})} \\
```
I just checked that there was no off-by-one error in the geometric series, and keeping the intermediate calculation doesn't hurt.

2025-12-22 21:17 UTC, tholop commented on rust/src/traits/samplers/cks20/sample_geometric_exp_fast.tex
> +\end{proof}
This whole theorem is not necessary, as pointed out by Michael. I suggest a fix in the final lemma showing how to replace this theorem.

2025-12-22 21:17 UTC, tholop commented on rust/src/traits/samplers/cks20/sample_geometric_exp_fast.tex
> +    then by \ref{geom_s_t}, \texttt{out} is distributed as $\textrm{Geometric}(1 - \exp(-x))$.
```suggestion
    then by \ref{divide_geometric}, $\lfloor Z / s \rfloor$ is distributed as $\textrm{Geometric}(1 - \exp(-s/t))$. Finally, $\texttt{out} = \lfloor Z / s \rfloor$ and $s/t = x$, so \texttt{out} is distributed as $\textrm{Geometric}(1 - \exp(-x))$.
```

2025-12-22 21:17 UTC, tholop commented on rust/src/traits/samplers/cks20/sample_geometric_exp_fast.tex
> +    As shown in \ref{err-e}, the preconditions for \rustdoc{traits/samplers/uniform/trait}{SampleUniformIntBelow} on line \ref{line:U},
Agreed with Michael's comments on the pdf, about (1) having the distribution for U, D, V in a lemma and (2) an explanation of what the loop is doing.

2026-04-20 06:03 UTC, Shoeboxam commented
@tholop I've got all the changes incorporated. Significant changes!

2026-06-05 21:20 UTC, tholop approved these changes
Looks good to me, thanks for the significant changes!

2026-06-05 21:20 UTC, merged