add `__version__`
opendp/opendp pull request #2139
Opened 2024-11-04 19:37 UTC by mccalluc

- Maybe fix #2103?
- Is this the right place for it? Maybe it belongs in `opendp`, not `opendp.prelude`?
- Right now I can't say that I understand the conditions when `VERSION` is not the version number.
- Do we need to clean up other places where `VERSION` is being read directly?

2024-12-20 23:45 UTC, Shoeboxam reviewed
It feels strange to me to have __VERSION__ in the prelude, but I'm also unsure where it should go, as we have multiple packages sharing the OpenDP namespace.

2025-01-07 19:15 UTC, mccalluc commented on python/src/opendp/prelude.py
> +__version__ = __get_opendp_version()
Define in mod instead: That's where top-level public stuff goes.

2025-01-08 16:50 UTC, mccalluc commented
`__version__` isn't picked up by `import *` because it starts with an underscore, so I added an `__all__`. Looking around noticed that there was only one other file where we import everything that didn't already have `__all__`, so fixed that too. This did surface a couple places where we were getting names (`np` and `re`) by accident, so tidy that up.

One question: Are `ELEMENTARY_TYPES`, `INTEGER_TYPES`, `NUMERIC_TYPES`, `HASHABLE_TYPES`, `PRIMITIVE_TYPES` intended to be part of the public interface, or not? I would guess not: Happy to clean that up in this PR, or can file a follow-up issue.

2025-01-09 15:42 UTC, Shoeboxam requested changes
Thanks for finding these. Feel free to fix the re-exports and drop visibility on those values here.

2025-01-09 15:42 UTC, Shoeboxam commented on python/src/opendp/typing.py
> +    # TODO: Are these intended to be part of the public interface?
They don't need to be, so IMO we don't make them part of the public interface.

2025-01-09 15:44 UTC, Shoeboxam requested changes

2025-01-09 15:44 UTC, Shoeboxam commented on python/src/opendp/typing.py
> +__all__ = [
I think we don't have to have version in prelude; could we avoid having `__all__` instead as it duplicates names? Or will that always cause imports to be re-exported?

2025-01-10 16:32 UTC, mccalluc commented on python/src/opendp/typing.py
> +__all__ = [
Sorry, I'm not quite understanding this.

> I think we don't have to have version in prelude

so `__version__` would be in `mod.py`, but unlike other names there, it would need to be explicitly imported? 
```
from opendp.mod import __version__
# or...
from opendp.mod
print(mod.__version__)
```
Apart from this, end users never need to use `mod` explicitly, so it feels weird to require it here.

2025-01-10 16:42 UTC, mccalluc commented on python/src/opendp/typing.py
> +__all__ = [
I'll take a stab at this, but wouldn't hurt to talk things through.

2025-01-23 03:21 UTC, Shoeboxam commented on python/src/opendp/mod.py
> +]
Do we still need this? It would be nice to not have to maintain it.

2025-01-23 13:23 UTC, mccalluc commented on python/src/opendp/mod.py
> +]
It's not absolutely necessary, but I think we do need to maintain a list of exports somewhere, for a couple reasons:
- Without `__all__`, `from opendp.mod import *` brings in all of the names, including this file's own imports, which clearly don't belong in this namespace.
- `import *` only brings in names without underscores, and doesn't include `__version__`.

An alternative would be to list everything to import instead of using `*`, but splitting it between two files seems like it would be more annoying. Other possibilities:
- Don't touch `mod.py` in this PR, and instead define `__version__` in `prelude.py`.
- Don't add `__all__`, and instead add an explicit import: `from opendp.mod import __version__`.

2025-01-23 17:08 UTC, Shoeboxam submitted a review, later dismissed
Thanks for your patience with my reviews!

2025-01-23 17:08 UTC, Shoeboxam commented on python/src/opendp/mod.py
> +]
Great point!

2025-01-23 23:53 UTC, mccalluc commented
To make sure it's doing the job, I've merged this branch into
- #2228

and it can be re-reviewed as part of that.

2025-01-23 23:53 UTC, closed without merging