Feedback form
opendp/opendp pull request #2154
Opened 2024-11-20 14:16 UTC by mccalluc

- Fix #2127. Surveyed other options, but this seems good enough. 

(If it's not good enough, then that's also good to know! I don't have any hard requirements right now to constrain the search.)

If you're working on this branch note that the iframe is a 403 if you're just loading it from `file:///`: It needs to be served by http.

Looks like this:

<img width="644" alt="Screenshot 2024-11-20 at 9 08 46 AM" src="https://github.com/user-attachments/assets/120d7f5c-b0a7-497c-9311-a296cc192afa">
<img width="642" alt="Screenshot 2024-11-20 at 9 09 08 AM" src="https://github.com/user-attachments/assets/c42f16da-c6f7-4474-b1c6-2781122a2024">

I've changed the font and text color to match our site, but it's still obviously a google form.

Questions to consider:
- Privacy wise, are we ok with a google form? One alternative would be to write out the html for the iframe only after the user clicks... but I think that would be a bit for work for not much gain.
- Are these questions the questions we want to ask?
- Whose responsibility is it to look at the responses?

2024-11-20 15:24 UTC, mccalluc commented
From Sharon on slack:
> Hmm, if that was the intent, a form doesn't seem like the right mechanism IMO.  Maybe something else can be explored

2024-12-03 16:24 UTC, mccalluc commented
Talked with Annie:
- These questions are good; could be simplified to just a thumbs up / down.
- Would like to know what page users are on.

Next steps:
- Google forms can be prepopulated, but I don't know that the prepopulation is transparent in the URL. If it is, great!
- If not, look at qualtrics: We've used it before, and billing is already set up.

Moving back to draft.

2024-12-04 22:49 UTC, mccalluc commented
Yes: Prefilled fields encoding isn't too tricky:

`space then/dash` becomes:

`https://docs.google.com/forms/d/e/1FAIpQLSeL-KZ_K1Yz5SOjGo0wYOLUEVbtOwBU1Ty6WeoRJbFWeEmD5w/viewform?entry.1628573312=space+then/dash`

2024-12-20 23:49 UTC, Shoeboxam commented
From running this myself, the 403 goes away if you update the settings of the form to allow folks from outside of Harvard to see it. However, it comes with a lot of invasive tracking that I can't disable through any cookies or javascript manipulation. 

Regardless, we should just provide invite links to the OpenDP Slack, email and github discussions so that we 
- don't dilute engagement 
- don't add more things to keep track of

2024-12-20 23:50 UTC, Shoeboxam requested changes
From running this myself, the 403 goes away if you update the settings of the form to allow folks from outside of Harvard to see it. However, it comes with a lot of invasive tracking that I can't disable through any cookies or javascript manipulation. 

Regardless, we should just provide invite links to the OpenDP Slack, email and github discussions so that we 
- don't dilute engagement 
- don't add more things to keep track of

2025-01-03 02:12 UTC, mccalluc commented
Updated the content, copying over the section from the README. I'd suggest some changes both here and there, though I don't want this to get bogged down.
- Drop twitter and github discussions
- Add security@opendp.org

Happy to make additional changes here, or in a follow-up PR, or just leave it as it: your call.

2025-01-07 19:53 UTC, Shoeboxam approved these changes
This looks great!

2025-01-08 13:16 UTC, merged