Vec<String> data loader
opendp/opendp pull request #218
Opened 2021-08-03 15:12 UTC by Shoeboxam

Closes #202

2021-08-09 18:30 UTC, andrewvyrros requested changes

2021-08-09 18:30 UTC, andrewvyrros commented on rust/opendp-ffi/src/data/mod.rs
> +        Ok(AnyObject::new(map))
I think we need to unpack the contents here?

2021-08-10 04:14 UTC, Shoeboxam commented on rust/opendp-ffi/src/lib.rs
> +#![recursion_limit="1024"]
I dropped it back to 512. This is for the cartesian product of generics when registering valid types of HashMaps in the static types array.

2021-08-10 14:46 UTC, andrewvyrros approved these changes
This is great, fills in a gap in Python access.

2021-08-10 14:47 UTC, merged