Checking docstrings, continued
opendp/opendp pull request #2182
Opened 2024-12-10 17:42 UTC by mccalluc

- Builds on #2181 
- If there is a docstring, param tags must match signature.

2024-12-20 23:56 UTC, Shoeboxam requested changes
As in the case of testing there are no prints, this seems like a nice test/nice to have, but could you work on filling the missing documentation in?

2025-01-03 19:29 UTC, mccalluc commented
Fill in TODOs, though not with anything particularly useful in most cases. In the future, I'd hope that checks like this would nudge us to provide something that does more than repeat the method name on new code, but for many of these, maybe that's enough.

Also [removed](https://github.com/opendp/opendp/pull/2182/files#diff-d8b5490a98400c6e71ac63fd5226bf1165657e2c8f969f6a4487cb6b08a5a921L440) one `eval` method that seems to be unused?

2025-01-03 19:37 UTC, mccalluc commented on python/src/opendp/typing.py
> +        TODO
@Shoeboxam , could you suggest a docstring here?

2025-01-07 19:44 UTC, mccalluc commented
rtype checking may already be working on this branch, but if other checks are strengthened, we might get more errors on it.

2025-01-07 19:53 UTC, mccalluc commented
Going forward: don't be strict about :rtype: and :type: annotations -- @mccalluc should remove any TODOs for those in this PR.

2025-01-16 10:07 UTC, Shoeboxam commented on python/src/opendp/typing.py
> +        TODO
Substitutes any generic type parameters according to the passed keyword arguments.

2025-01-16 10:30 UTC, Shoeboxam requested changes
Lots of small cleanups in here and some future-proofing.

2025-01-16 10:30 UTC, Shoeboxam commented on python/src/opendp/extras/polars/__init__.py
> +            :param on:
```suggestion
            :param keys: lazyframe containing a key-set whose columns correspond to the grouping keys
            :param on: optional, the names of columns to join on. Useful if the key dataframe contains extra columns
```

2025-01-16 10:30 UTC, Shoeboxam commented on python/src/opendp/extras/numpy/__init__.py
> +    :param T:
```suggestion
    :param T: the type of data elements in the array
```

2025-01-16 10:30 UTC, Shoeboxam commented on python/src/opendp/context.py
> +        :param wrap_release:
```suggestion
        :param chain: the prior query. Either a metric space or transformation
        :param wrap_release: a function to apply to apply to releases
```

2025-01-16 10:30 UTC, Shoeboxam commented on python/src/opendp/context.py
> +            :param kwargs:
```suggestion
            :param args: arguments for the constructor function
            :param kwargs: keyword arguments for the constructor function
```

2025-01-16 10:30 UTC, Shoeboxam commented on python/src/opendp/extras/polars/__init__.py
> +            :param named_aggs:
```suggestion
            :param aggs: expressions to apply in the aggregation context
            :param named_aggs: named/aliased expressions to apply in the aggregation context
```

2025-01-16 10:30 UTC, Shoeboxam commented on python/src/opendp/extras/polars/__init__.py
> +            :param alpha:
```suggestion
            :param alpha: optional. A value in [0, 1] denoting the statistical significance.
```

2025-01-16 10:30 UTC, Shoeboxam commented on python/src/opendp/mod.py
> +        :param d_in: Input distance
```suggestion
        :param d_in: Input distance. An upper bound on how far apart neighboring datasets can be with respect to the input metric
```

2025-01-16 10:30 UTC, Shoeboxam commented on python/src/opendp/mod.py
> +        :param val:
```suggestion
        :param val: a value to be checked for membership in `self`
```

2025-01-16 10:30 UTC, Shoeboxam commented on python/src/opendp/mod.py
> +        Descriptor of domain
```suggestion
        Descriptor of domain. Used to retrieve the descriptor associated with domains defined in Python 
```

2025-01-16 10:30 UTC, Shoeboxam commented on python/src/opendp/mod.py
> +        :param epsilon:
```suggestion
        :param epsilon: Allowance for a multiplicative difference, or max divergence, in the distributions of releases on adjacent datasets
```

2025-01-16 10:30 UTC, Shoeboxam commented on python/src/opendp/mod.py
> +        :param delta:
```suggestion
        :param epsilon: Allowance for an additive difference between the distributions of releases on adjacent datasets
```

2025-01-16 17:31 UTC, mccalluc commented on python/src/opendp/extras/polars/__init__.py
> +            :param alpha:
Since `1 - alpha` comes up frequently, I'll add that here as well.

2025-01-16 17:33 UTC, mccalluc commented on python/src/opendp/typing.py
> +        TODO
```suggestion
        Substitutes any generic type parameters according to the passed keyword arguments
```

2025-01-23 23:56 UTC, Shoeboxam approved these changes

2025-01-24 20:52 UTC, mccalluc commented on python/src/opendp/mod.py
> +        :param at_center:
Thanks! I'll apply this suggestion on #2242 so the change doesn't clear your approval.

2025-01-24 20:54 UTC, merged