333 resize notebook
opendp/opendp pull request #387
Opened 2021-10-29 21:53 UTC by ecowan

Closes #333

2021-11-09 20:50 UTC, Shoeboxam requested changes
I made a pass through:
- made the old section of the notebook match with the new section
- switched the old section to use means instead of sums (fp is more stable now)
- pass Vec<f64> in, instead of parsing from a csv string. Simplifies the chains
- add bounds to the binary search calls to make things run quickly
- adjusted the epsilon value of the count estimate down, to fix the graphs
- rewrote most of the latter sections to simplify the implementation

We still need some more exposition around the boxes in the latter portion.

2022-01-06 00:53 UTC, ecowan commented on python/example/unknown_dataset_size.ipynb
> +  {
Agreed, I'm rewording

2022-01-06 00:53 UTC, ecowan commented on python/example/unknown_dataset_size.ipynb
> +  {
I'm not sure which line in particular this is referring to?

2022-01-11 16:09 UTC, Shoeboxam commented on python/example/unknown_dataset_size.ipynb
> +  {
Cells 43-46 have no explanation/interpretation/accompanying text.

2022-02-08 13:46 UTC, Shoeboxam commented
Force-pushed to rid history of the accuracy notebook, to fix the merge conflict.

2022-02-08 16:07 UTC, Shoeboxam approved these changes

2022-02-09 00:47 UTC, merged