binary search fixes
opendp/opendp pull request #453
Opened 2022-04-06 09:44 UTC by Shoeboxam

Closes #443 
Fixes an infinite loop due to floating-point roundoff when distance to nearest neighbor is greater than tolerance.
Adjusts the tolerance to 0., because we have a better stopping criteria.
Improves the efficiency of binary search, as it doesn't search all positive floats, it works up in powers of 2 from more commonly used parameters.
Adds a default argument to bounds on `binary_search`.

2022-04-11 23:12 UTC, andrewvyrros requested changes
This is a nice improvement! Just could use a few tiny tweaks.

2022-04-12 01:15 UTC, Shoeboxam commented on python/src/opendp/mod.py
> -    :param tolerance: the discovered parameter differs by at most `tolerance` from the ideal parameter
Ah, it was eaten up in a rebase. Thanks for pointing this out.

2022-04-12 14:50 UTC, andrewvyrros approved these changes

2022-04-12 14:50 UTC, merged

2022-04-19 17:39 UTC, joshua-oss commented
Looks great; thanks!!

2022-05-17 18:38 UTC, joshua-oss commented
BTW, would it be possible to get a release for this?  I would like to up the dependency for our synthesizers, since it looks like we are running into the issue when people use large epsilon