make Queryable from Python UDF
opendp/opendp pull request #870
Opened 2023-07-12 23:29 UTC by Shoeboxam

Closes #851

2023-07-12 23:29 UTC, Shoeboxam commented
Current dependencies on/for this PR:
* main
  * **PR #870** <a href="https://app.graphite.dev/github/pr/opendp/opendp/870" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈
    * **PR #871** <a href="https://app.graphite.dev/github/pr/opendp/opendp/871" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/opendp/opendp/870?utm_source=stack-comment).

2023-08-22 17:12 UTC, andrewvyrros requested changes

2023-08-22 17:12 UTC, andrewvyrros commented on python/test/test_interactive.py
> +    print("after transition", qbl([2, 3]))
Could you assert these?

2023-08-22 17:12 UTC, andrewvyrros commented on rust/src/combinators/user_defined/ffi.rs
> +fn wrap_trans(
Minor: This is ambiguous with transformation, would suggest `wrap_transition`.

2023-08-23 03:37 UTC, Shoeboxam commented
Added 2 new commits

2023-08-24 14:40 UTC, andrewvyrros approved these changes
Thanks for tweaking the tests!

2023-08-24 18:41 UTC, merged