add `UserDistance` and `UserDivergence`
opendp/opendp pull request #873
Opened 2023-07-13 05:51 UTC by Shoeboxam

Closes #872

2023-07-13 05:51 UTC, Shoeboxam commented
Current dependencies on/for this PR:
* main
  * **PR #870** <a href="https://app.graphite.dev/github/pr/opendp/opendp/870" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #871** <a href="https://app.graphite.dev/github/pr/opendp/opendp/871" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #873** <a href="https://app.graphite.dev/github/pr/opendp/opendp/873" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/opendp/opendp/873?utm_source=stack-comment).

2023-08-22 17:37 UTC, andrewvyrros requested changes

2023-08-22 17:37 UTC, andrewvyrros commented on python/test/test_core.py
> +    print(trans.map(timedelta(days=2.4, seconds=45.2)))
It'd be good to assert these.

2023-08-24 22:29 UTC, andrewvyrros approved these changes

2023-08-24 22:30 UTC, merged